### ISSUE TITLE
Get-ComputerInformation -Name "Server1"  Error

### ISSUE THREAD

**Issue by red-erik** [BenPetersonIT/Glance#17]
Hello,
thank you for sharing you work. I'm doing some test and had problems with Get-ComputerInformation.
Hitting "Get-ComputerInformation -Name "Server1"" ans in you example I receive

`ForEach-Object : Parameter set cannot be resolved using the specified named parameters.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSSystemAdministrator\PSSystemAdministrator.psm1:894 char:22
+         $computers | ForEach-Object -Parallel {
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (:) [ForEach-Object], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.PowerShell.Commands.ForEachObjectCommand`

Something wrong with a single Computername in ForEach cycle.

It **works** with
Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      0      2

It does **NOT** work with
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      14393  3866

Regards,

Red.

**Comment by benponline** [comment]
Sorry to hear its not working for you. I did some testing and I think I know what the problem is. I recently updated some of the functions to use `ForEach-Object -Parrallel`. That command is only compatible with PowerShell Core. If you are using an older version of PowerShell you will get that error. If you download PowerShell Core from [here](https://github.com/PowerShell/PowerShell), the command should start working for you.

Let me know if that doesn't work for you.

**Comment by red-erik** [comment]
Hello,
for sure it works but it would be better to underline it in the "requirements" where you have:
"This module is written for PowerShell Core and tested with Windows 10 machines, but should be mostly compatible with PowerShell 5 and Windows 7. I am actively developing this module alongside my work as a system administrator. I use this module every day."
It would be nice to add "some of the enhanced features, like parallel processing, are present in powershell core and powershell 7 only."

Regards,

Red.

**Comment by benponline** [comment]
Good point. I removed the part about PowerShell 5 and Windows 7.  As the module develops, most of the functions will likely only work on PowerShell Core.

Thanks

**Comment by red-erik** [comment]
Another idea would be to drop a line on how to install the module on Powershell Core on different OS (eg. Linux) ;-)

Red.
